name: heroku-deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "multiple-filters-react-redux"
          heroku_email: "manuelmenendezalfonso@gmail.com"

      - name: Run a one-line script
        run: echo successfully run
